spring:
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:librarydb
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        jdbc:
          core: error
